# Generated by Django 5.0.2 on 2024-03-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(upload_to='docx/'),
        ),
    ]
